name: 'ICC_APP Action'
description: 'GitHub Action for ICC_APP deployment'
author: 'T-lamo'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub  token for authentication'
    required: true

  publish_dir:
    description: 'Directory to publish'
    required: true
    default: 'dist'

runs:
  using: 'node12'
  main: 'index.js'
