name: Angular Project CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: ng build --prod

    #   - name: Deploy to GitHub Pages
    #     if: github.ref == 'refs/heads/main'
    #     uses: peaceiris/gh-pages-deploy-action@v3
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: dist