name: ICCNG CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.0.0'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: ng build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/develop'
        uses: 'T-lamo/ICC_APP@v1.0.3'
        with:
            github_token: ${{ secrets.ICC_TOKEN }}
            publish_dir: dist